{
 "title": "DB Request",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Запросы Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_stats_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы CalculatedStats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_calculatedStats{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_users_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы UserSession",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_userSession_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы Keywords",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_keywords_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы PersonalInfo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_personalInfo_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы Admins",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_admins_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запросы Cron",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_cron_total{instance=\"botstats-api-1:4000\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}