{
 "title": "Requests dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cредняя длительность запроса Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_stats_duration_sum[5m])\r\n/\r\nrate(db_request_stats_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_stats_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Среднее время обработки запросов UserSession",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_userSession_duration_sum[5m])\r\n/\r\nrate(db_request_userSession_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы UserSession",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_userSession_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cредняя длительность запроса Cron",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_cron_duration_sum[5m])\r\n/\r\nrate(db_request_cron_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы Cron",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_cron_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cредняя длительность запроса CalculatedStats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_calculatedStats_duration_sum[5m])\r\n/\r\nrate(db_request_calculatedStats_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы CalculatedStats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_calculatedStats_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cредняя длительность запроса User",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_users_duration_sum[5m])\r\n/\r\nrate(db_request_users_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы User",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_users_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cредняя длительность запроса PersonalInfo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_personalInfo_duration_sum[5m])\r\n/\r\nrate(db_request_personalInfo_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы PersonalInfo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_personalInfo_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cредняя длительность запроса Admin",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_admins_duration_sum[5m])\r\n/\r\nrate(db_request_admins_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы Admin",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_admins_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Средняя длительность запроса Keyword",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_request_keywords_duration_sum[5m])\r\n/\r\nrate(db_request_keywords_duration_count[5m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Запросы Keywords",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_request_keywords_total[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}