{
 "title": "Loki stack monitoring (Promtail, Loki)",
 "description": "This dashboard can be used to detect issues on the Loki stack, when deployed in Kubernetes. Shows: some error metrics published by Promtail/Loki. Error and warning logs emitted by Promtail/Loki.",
 "tags": [
  "tools",
  "loki"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "All logs from API",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"botstats-api-1\"}"
    }
   ]
  },
  {
   "title": "Erorr logs from Api",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"botstats-api-1\"} |~ `(?i)ERROR`"
    },
    {}
   ]
  },
  {
   "title": "Warn logs from Api",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"botstats-api-1\"} |~ `(?i)WARN`"
    },
    {}
   ]
  },
  {
   "title": "All logs from kafka",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container=\"botstats-kafka-1\"}"
    },
    {}
   ]
  },
  {
   "title": "All logs from zookeeper",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{container=\"botstats-zookeeper-1\"}"
    },
    {}
   ]
  },
  {
   "title": "All logs from postgres",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{container=\"botstats-postgres-1\"}"
    },
    {}
   ]
  }
 ]
}